# -*- coding: utf-8 -*-
"""SMS_Spam_SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSThX7zJNAAIjHNjg195UG92stJpx8Y6

# SMS Spam Classification using SVM
Dataset: https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset?resource=download
"""

# Install (if needed)
!pip -q install wordcloud nltk scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from wordcloud import WordCloud
import re, string, nltk
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import (accuracy_score,classification_report,
confusion_matrix,ConfusionMatrixDisplay,
precision_score,recall_score,f1_score,roc_curve,auc)

nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

"""## Upload dataset (`spam.csv`) downloaded from Kaggle."""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("spam.csv", encoding="latin-1")

df = df[['v1', 'v2']]

df.columns = ['label', 'message']

print(df.shape)
print(df.info())
print(df.isnull().sum())
print("Duplicates:",df.duplicated().sum())
print(df['label'].value_counts())

"""## Exploratory Data Analysis"""

df['char_count']=df['message'].str.len()
df['word_count']=df['message'].str.split().str.len()

fig,ax=plt.subplots(1,2,figsize=(10,4))
sns.countplot(data=df,x='label',ax=ax[0])
sns.histplot(data=df,x='word_count',hue='label',bins=30,ax=ax[1])
plt.tight_layout()
plt.show()

spam=' '.join(df[df.label=='spam'].message)
ham=' '.join(df[df.label=='ham'].message)

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.imshow(WordCloud(background_color='white').generate(spam))
plt.axis('off'); plt.title("Spam")
plt.subplot(1,2,2)
plt.imshow(WordCloud(background_color='white').generate(ham))
plt.axis('off'); plt.title("Ham")
plt.show()

"""## Preprocessing"""

# Load the list of English stopwords (e.g., "the", "is", "and")
stop_words = set(stopwords.words('english'))

# Create a WordNet lemmatizer object to convert words to their base form
lemm = WordNetLemmatizer()

# Define a function to clean and preprocess SMS text
def clean_text(text):

    # Convert all characters to lowercase
    text = text.lower()

    # Remove URLs (e.g., http://example.com or www.example.com)
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove email addresses (e.g., abc@gmail.com)
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove all numeric digits from the text
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation marks such as !, ?, ., ,, :, etc.
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Split the sentence into words,
    # remove stopwords,
    # and convert each word to its base (lemma) form
    tokens = [
        lemm.lemmatize(word)
        for word in text.split()
        if word not in stop_words
    ]

    # Join the cleaned words back into a single string
    return ' '.join(tokens)

# Remove duplicate SMS messages from the dataset
df = df.drop_duplicates()

# Apply the clean_text() function to every message
# and store the cleaned text in a new column named 'clean_message'
df['clean_message'] = df['message'].apply(clean_text)

# Convert categorical labels into numerical values
# ham  -> 0
# spam -> 1
df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

# Display the first five rows of the processed dataset
df.head()

"""## Train/Test Split"""

from sklearn.model_selection import train_test_split

X = df['clean_message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

"""## SVM Model"""

pipeline=Pipeline([
('tfidf',TfidfVectorizer(max_features=5000,ngram_range=(1,2))),
('svm',LinearSVC())
])

pipeline.fit(X_train,y_train)
pred=pipeline.predict(X_test)

print("Accuracy:",accuracy_score(y_test,pred))
print("Precision:",precision_score(y_test,pred))
print("Recall:",recall_score(y_test,pred))
print("F1:",f1_score(y_test,pred))
print(classification_report(y_test,pred))

"""## Hyperparameter Tuning"""

param_grid={
'svm__C':[0.1,1,10]
}
grid=GridSearchCV(pipeline,param_grid,cv=5,n_jobs=-1)
grid.fit(X_train,y_train)

print("Best Parameters:",grid.best_params_)
print("Best CV Score:",grid.best_score_)

"""## Cross Validation"""

scores=cross_val_score(grid.best_estimator_,df['clean_message'],df['label'],cv=5)
print(scores)
print("Mean Accuracy:",scores.mean())

"""## Prediction Function"""

model=grid.best_estimator_

def predict_sms(text):
    pred=model.predict([clean_text(text)])[0]
    return "Spam" if pred==1 else "Ham"

print(predict_sms("Hi, you've won a lottery. COllect the prize money by paying $100 now."))
print(predict_sms("Collect free vacation! Click the link below:"))

"""# Task
The goal is to classify SMS messages as either 'spam' or 'ham' (not spam) using a Support Vector Machine (SVM) model. The project involves loading and preprocessing a dataset, performing exploratory data analysis, training an SVM model with TF-IDF features, tuning hyperparameters using GridSearchCV, evaluating the model's performance with cross-validation and various metrics (accuracy, precision, recall, F1-score), and finally creating an interactive prediction function.

Additional tasks include:
* **Visualize Confusion Matrix**: Generate and display a confusion matrix for the SVM model's predictions on the test set to visualize the true positives, true negatives, false positives, and false negatives.
* **Plot ROC Curve**: Calculate and plot the Receiver Operating Characteristic (ROC) curve and the Area Under the Curve (AUC) for the SVM model to evaluate its performance across various classification thresholds.
* **Compare with Naive Bayes Classifier**: Implement a Naive Bayes classifier (e.g., Multinomial Naive Bayes) with TF-IDF features and compare its performance metrics (accuracy, precision, recall, F1-score, confusion matrix, ROC curve) against the current SVM model.
* **Interactive Prediction Widget**: Develop an interactive widget using `ipywidgets` that allows a user to input a text message and receive an instant 'Spam' or 'Ham' prediction from the trained model. This will personalize the project by making it directly usable for message classification.
* **Final Task**: Summarize the additional analysis and model comparison results, discuss the insights gained from the visualizations, and highlight the functionality of the interactive prediction tool.

## Visualize Confusion Matrix

### Subtask:
Generate and display a confusion matrix for the SVM model's predictions on the test set.

**Reasoning**:
Generate and display the confusion matrix for the SVM model's predictions on the test set.
"""

cm = confusion_matrix(y_test, pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Ham', 'Spam'])
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for SVM Model')
plt.show()

"""## Plot ROC Curve

### Subtask:
Calculate and plot the Receiver Operating Characteristic (ROC) curve and the Area Under the Curve (AUC) for the SVM model to evaluate its performance across various classification thresholds.

**Reasoning**:
Calculate the decision function scores for the positive class (spam) from the trained SVM model on the test data. Since LinearSVC doesn't directly output probabilities, use `decision_function`.
"""

y_scores = model.decision_function(X_test)
y_scores

"""**Reasoning**:
Calculate the False Positive Rate (fpr), True Positive Rate (tpr), and Area Under the Curve (AUC) using the true labels (`y_test`) and the decision function scores (`y_scores`). These values are necessary to plot the ROC curve.


"""

fpr, tpr, thresholds = roc_curve(y_test, y_scores)
roc_auc = auc(fpr, tpr)

print(f"Area Under the Curve (AUC): {roc_auc:.4f}")

"""**Reasoning**:
Now that we have calculated the FPR, TPR, and AUC, the next step is to plot the ROC curve to visually represent the model's performance.


"""

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for SVM Model')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""## Compare with Naive Bayes Classifier

### Subtask:
Implement a Naive Bayes classifier (e.g., Multinomial Naive Bayes) with TF-IDF features and compare its performance metrics (accuracy, precision, recall, F1-score, confusion matrix, ROC curve) against the current SVM model.

**Reasoning**:
This step implements the Naive Bayes classifier using a pipeline with TF-IDF features, trains it, and evaluates its initial performance metrics (accuracy, precision, recall, F1-score, and classification report) on the test set, which is the first part of comparing it with the SVM model.
"""

from sklearn.naive_bayes import MultinomialNB

nb_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2))),
    ('nb', MultinomialNB())
])

nb_pipeline.fit(X_train, y_train)
nb_pred = nb_pipeline.predict(X_test)

print("Naive Bayes Model Performance:")
print("Accuracy:", accuracy_score(y_test, nb_pred))
print("Precision:", precision_score(y_test, nb_pred))
print("Recall:", recall_score(y_test, nb_pred))
print("F1:", f1_score(y_test, nb_pred))
print(classification_report(y_test, nb_pred))

"""**Reasoning**:
Generate and display the confusion matrix for the Naive Bayes model's predictions on the test set.


"""

cm_nb = confusion_matrix(y_test, nb_pred)
disp_nb = ConfusionMatrixDisplay(confusion_matrix=cm_nb, display_labels=['Ham', 'Spam'])
disp_nb.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Naive Bayes Model')
plt.show()

"""**Reasoning**:
Calculate the predicted probabilities for the positive class (spam) using the trained Naive Bayes model on the test data. This is necessary to compute the ROC curve and AUC for the Naive Bayes model.


"""

nb_y_probs = nb_pipeline.predict_proba(X_test)[:, 1]
nb_y_probs

"""**Reasoning**:
Calculate the False Positive Rate (fpr), True Positive Rate (tpr), and Area Under the Curve (AUC) using the true labels (`y_test`) and the predicted probabilities (`nb_y_probs`). These values are necessary to plot the ROC curve for the Naive Bayes model.


"""

fpr_nb, tpr_nb, thresholds_nb = roc_curve(y_test, nb_y_probs)
roc_auc_nb = auc(fpr_nb, tpr_nb)

print(f"Area Under the Curve (AUC) for Naive Bayes: {roc_auc_nb:.4f}")

"""**Reasoning**:
Now that we have calculated the FPR, TPR, and AUC for the Naive Bayes model, the next step is to plot the ROC curve to visually represent the model's performance.


"""

plt.figure(figsize=(8, 6))
plt.plot(fpr_nb, tpr_nb, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc_nb:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for Naive Bayes Model')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""## Interactive Prediction Widget

### Subtask:
Develop an interactive widget using `ipywidgets` that allows a user to input a text message and receive an instant 'Spam' or 'Ham' prediction from the trained model.

**Reasoning**:
Import `Text`, `Button` from `ipywidgets` and `display`, `clear_output` from `IPython.display` to create and manage the interactive prediction widget.
"""

from ipywidgets import Text, Button, Output
from IPython.display import display, clear_output

print("Required ipywidgets and IPython.display modules imported.")

"""**Reasoning**:
Create the Text input widget for the user to type their message and the Button widget to trigger the prediction. The text input will be initialized with a placeholder message.


"""

text_input = Text(value='Enter your SMS message here...', description='Message:')
predict_button = Button(description='Predict')
output_area = Output()

print("Text input, predict button, and output area widgets created.")

"""**Reasoning**:
Define the event handler function for the predict button. This function will take the text from the `text_input` widget, clean it using the `clean_text` function, make a prediction using the `predict_sms` function (which utilizes the trained SVM model), and then display the result in the `output_area`.


"""

def on_predict_button_clicked(b):
    with output_area:
        clear_output(wait=True)
        message = text_input.value
        prediction = predict_sms(message)
        print(f"Prediction: {prediction}")

predict_button.on_click(on_predict_button_clicked)

display(text_input, predict_button, output_area)

print("Interactive prediction widget displayed and ready for use.")

"""## Final Task

### Subtask:
Summarize the additional analysis and model comparison results, discuss the insights gained from the visualizations, and highlight the functionality of the interactive prediction tool.

### Final Task Summary

This project successfully developed and evaluated an SMS spam classification model. Here's a summary of the key findings and the interactive tool:

#### Model Comparison: SVM vs. Naive Bayes
We compared a Support Vector Machine (SVM) model with a Multinomial Naive Bayes (MNB) model, both utilizing TF-IDF features for text representation. The performance metrics are summarized below:

*   **SVM Model (LinearSVC)**:
    *   Accuracy: 0.9845
    *   Precision (Spam): 0.9832
    *   Recall (Spam): 0.8931
    *   F1-score (Spam): 0.9360
    *   AUC: 0.9958
    *   Confusion Matrix Observations: The SVM model showed excellent performance, correctly classifying 901 'Ham' messages and 117 'Spam' messages. It had only 2 False Positives (Ham classified as Spam) and 14 False Negatives (Spam classified as Ham). Its high AUC indicates strong discriminative power.

*   **Naive Bayes Model (MultinomialNB)**:
    *   Accuracy: 0.9681
    *   Precision (Spam): 0.9900
    *   Recall (Spam): 0.7557
    *   F1-score (Spam): 0.8571
    *   AUC: 0.9899
    *   Confusion Matrix Observations: The Naive Bayes model also performed well, correctly classifying 902 'Ham' messages and 99 'Spam' messages. Notably, it had only 1 False Positive, indicating very high precision for spam detection. However, it had 32 False Negatives, meaning it missed more spam messages compared to SVM.

**Conclusion on Model Comparison**: The **SVM model generally outperformed the Naive Bayes model** in terms of overall accuracy, recall for spam messages, F1-score, and AUC. While Naive Bayes showed slightly higher precision for spam, SVM had a better balance of precision and recall, making it more robust for this task. The SVM model's ability to minimize both false positives and false negatives is crucial for a spam classifier.

#### Insights from Exploratory Data Analysis
*   **Class Imbalance**: The dataset showed a significant class imbalance, with 'ham' messages being much more frequent than 'spam' messages (4825 ham vs. 747 spam after duplicate removal).
*   **Message Length**: Spam messages generally tended to be longer in terms of word count and character count compared to ham messages, as indicated by the histplot. This is a common characteristic, as spam often includes promotional text, links, and disclaimers.
*   **Word Clouds**: The word clouds provided visual insights into common terms. The 'Spam' word cloud highlighted terms like 'free', 'call', 'txt', 'win', 'prize', 'mobile', and 'urgent', which are characteristic of promotional or scam messages. The 'Ham' word cloud contained more general conversational terms like 'go', 'know', 'love', 'get', 'like', and 'time', reflecting everyday communication.

#### Interactive Prediction Widget Functionality
The developed interactive widget provides a user-friendly interface for real-time spam detection. Users can input any SMS message into a text box and click a 'Predict' button to instantly receive a 'Spam' or 'Ham' classification. This tool personalizes the project, making the trained model directly accessible and usable for practical message classification by anyone. It demonstrates the direct application of the machine learning model in a tangible way.

#### Final Thoughts and Next Steps
This project successfully built an effective SMS spam classifier. To further enhance the model, potential next steps could include:
*   **Advanced Text Preprocessing**: Experimenting with more sophisticated text normalization techniques or incorporating n-grams beyond bigrams.
*   **Feature Engineering**: Adding more features such as the number of special characters, presence of all-caps words, or sentiment scores.
*   **Ensemble Methods**: Exploring ensemble models (e.g., RandomForest, Gradient Boosting) or stacking different classifiers.
*   **Deep Learning Models**: Investigating neural network architectures like LSTMs or Transformers for potentially higher accuracy in text classification tasks, especially with larger datasets.
*   **User Feedback Integration**: Implementing a mechanism to collect user feedback on predictions to continuously improve the model over time.
"""